version: '3.8'
services:
  tropical_db:
    image: mysql:latest
    networks:
      - tropical-network
    restart: always
    ports:
      - "${DKDB_PORT}:${DB_PORT}"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
      MYSQL_DATABASE: ${DB_DATABASE}
    container_name: ${DB_HOST}
    volumes:
      - ./tropical-v06-1804.sql:/docker-entrypoint-initdb.d/tropical-v06-1804.sql
      - ./${DB_HOST}:/var/lib/mysql
  tropicaldapp:
    depends_on:
      - tropical_db
    build:
      context: .
      dockerfile: Dockerfile
    image: tropicalapp:1.0.0
    networks:
      - tropical-network
    container_name: TropicalApp
    restart: always
    ports:
      - "${APP_PORT}:${APP_PORT}"
    environment:
      PORT: ${APP_PORT}
      JWT_SECRETO: ${JWT_SECRETO}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_DATABASE: ${DB_DATABASE}
      DB_DIAL: ${DB_DIAL}
volumes:
  tropical_db:
networks:
  tropical-network: